### ISSUE TITLE
Delay between sending keys

### ISSUE THREAD

**Issue by prbtt** [jaruba/ha-samsungtv-tizen#94] opened 2020-10-17 22:21 UTC
There appears to be a 2 sec delay between sending keys. For example: If I want to navigate 2 times to the left, It takes about 2 secs for the second command to register. Is there a way to change that?

Edit: I realised this delay only happens with the service media_player.play_media, which is used to see keys.

**Comment by jaruba** [comment] 2020-10-18 08:14
I can confirm this is an issue, for now it seems to be caused by HA's decision to not allow synchronous logic anymore.

I'm going to write my thoughts on this here as it's a puzzle that should be solved.

The actual problems:
- As we're forced to use async now everything takes a longer time complete, and awaiting for one key to finish sending in order to send a new key causes the ~2s delay
- Why does it take ~2s for the keys to be sent through the WebSocket connection?

I'd say that this is where the issue originates:
https://github.com/jaruba/ha-samsungtv-tizen/blob/master/custom_components/samsungtv_tizen/media_player.py#L797-L800

But given the complications of ensuring that WebSocket keys and SmartThings keys need to be sent consecutively, it could possibly be fixed in any number of places throughout the code.

I tested changing the lines i linked above to:
```
  else:
    time.sleep(0.5)
    if this_key.startswith("ST_"):
      self.hass.async_add_job(self._smartthings_keys, this_key)
    else:
      self.hass.async_add_job(self.send_command, this_key)
```

The change would presume that it won't wait for a key to finish sending before sending a new one, but it adds a 500ms delay between sending keys. This made the keys run much faster, one right after the other.

But the first ever time I tested with it, it only sent `KEY_2` and `KEY_ENTER` instead of `KEY_1+KEY_5+KEY_2+KEY_ENTER`, after that it just worked like a charm..

The issue with the missing keys after this change is probably caused by the fact that the WebSocket connection was closed when the first key was sent. The logic also dictates that if a WebSocket connection was not used for 10s, then it will be forcefully closed: https://github.com/jaruba/ha-samsungtv-tizen/blob/master/custom_components/samsungtv_tizen/media_player.py#L474 

So this is more problematic to solve in this case, because when sending keys, if the connection is closed, it will try to reconnect automatically on each key sent. But if we will send keys at a 0.5s difference between them (instead of waiting for each to finish) it may cause a race condition in the reconnection logic.

It's highly probable that I'm looking at this wrongly, and the `send_command` function is the one that needs to be debugged to figure out why it takes 2s in the first place..

**Comment by jaruba** [comment] 2020-10-18 10:12
@prbtt 
I released a new version that sets the default delay between keys to `500` (milliseconds), so `KEY_1+KEY_ENTER` is now equal to `KEY_1+500+KEY_ENTER`. You can also increase or decrease this time by manually setting the delay, for example `KEY_1+250+KEY_ENTER` will reduce the timeout to 250ms between the keys.

Test it, tell me if it works better for you now. I'm closing the issue for now, if it still doesn't work as expected for you, then you can reopen the ticket.

**Closed by jaruba** 2020-10-18 10:12 UTC
