### ISSUE TITLE
Url for persons not in EU/US in documentation

### ISSUE THREAD

**Issue by fusionstream** [jaruba/ha-samsungtv-tizen#113] opened 2021-01-10 09:30 UTC
Visit:
https://graph.api.smartthings.com/location/list

Find your devices there. Be sure to actually click on the device as the _device network id_ listed there is not what you want.

**Comment by Screwdgeh** [comment] 2021-01-20 13:54
This is now updated in the documentation for non EU/US users. Therefore closing this.

Duplicate of #119.

**Closed by Screwdgeh** 2021-01-20 13:54 UTC
